#  Word2vec

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann
* https://radimrehurek.com/gensim/models/word2vec.html
* https://radimrehurek.com/gensim/auto_examples/tutorials/run_word2vec.html
* https://github.com/OlgaChernytska/word2vec-pytorch
* https://www.baeldung.com/cs/nlps-word2vec-negative-sampling
* https://towardsdatascience.com/implementing-word2vec-in-pytorch-from-the-ground-up-c7fe5bf99889

## Задачи для совместного разбора

1\. Рассмотрите основные шаги подготовки данных для обучения skip-gram модели

In [1]:
text = "Рассмотрите основные шаги подготовки данных для обучения".lower()
tokens = text.split()
tokens

['рассмотрите', 'основные', 'шаги', 'подготовки', 'данных', 'для', 'обучения']

In [2]:
indices = [tokens.index(tok) for tok in tokens]
indices

[0, 1, 2, 3, 4, 5, 6]

In [3]:
import torch as th
# k = 3

x = []
y = []
for idx in range(1, len(indices)-1):
  x.append(indices[idx])
  y.append(indices[idx-1])
  x.append(indices[idx])
  y.append(indices[idx+1])
x = th.tensor(x)
y = th.tensor(y)

In [4]:
x

tensor([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [5]:
y

tensor([0, 2, 1, 3, 2, 4, 3, 5, 4, 6])

2\. Рассмотрите основные шаги по настройке skip-gram модели

In [6]:
import torch.nn as nn

vocab_size = len(set(tokens))

embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=2)
linear = nn.Linear(in_features=2, out_features=vocab_size)

e = embedding(x)
out = linear(e)
out

tensor([[ 0.7967,  0.0430, -0.6052, -0.1971, -0.6298,  0.1592,  0.2922],
        [ 0.7967,  0.0430, -0.6052, -0.1971, -0.6298,  0.1592,  0.2922],
        [ 1.1955,  0.1308, -1.0205, -0.6181, -0.8221,  0.1459,  0.5732],
        [ 1.1955,  0.1308, -1.0205, -0.6181, -0.8221,  0.1459,  0.5732],
        [-0.2348, -0.1924,  0.4555,  0.8887, -0.0956,  0.2022, -0.4041],
        [-0.2348, -0.1924,  0.4555,  0.8887, -0.0956,  0.2022, -0.4041],
        [ 0.2118,  0.0555,  0.2257,  0.4694, -0.9560,  0.0336, -0.6256],
        [ 0.2118,  0.0555,  0.2257,  0.4694, -0.9560,  0.0336, -0.6256],
        [ 0.1790, -0.0664,  0.0796,  0.4641, -0.4460,  0.1525, -0.2378],
        [ 0.1790, -0.0664,  0.0796,  0.4641, -0.4460,  0.1525, -0.2378]],
       grad_fn=<AddmmBackward0>)

## Задачи для самостоятельного решения

In [11]:
import pandas as pd
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to C:\Users\Rog
[nltk_data]     G16\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


<p class="task" id="1"></p>

1\. Загрузите тексты новостей из файла `news_500.csv`. Удалите из текстов все знаки препинания и символы не из русского алфавита, приведите все слова к нижнему регистру и удалите стоп-слова.

- [ ] Проверено на семинаре

In [ ]:
stop_words = set(stopwords.words('russian'))
stop_words

{'а',
 'без',
 'более',
 'больше',
 'будет',
 'будто',
 'бы',
 'был',
 'была',
 'были',
 'было',
 'быть',
 'в',
 'вам',
 'вас',
 'вдруг',
 'ведь',
 'во',
 'вот',
 'впрочем',
 'все',
 'всегда',
 'всего',
 'всех',
 'всю',
 'вы',
 'где',
 'да',
 'даже',
 'два',
 'для',
 'до',
 'другой',
 'его',
 'ее',
 'ей',
 'ему',
 'если',
 'есть',
 'еще',
 'ж',
 'же',
 'за',
 'зачем',
 'здесь',
 'и',
 'из',
 'или',
 'им',
 'иногда',
 'их',
 'к',
 'как',
 'какая',
 'какой',
 'когда',
 'конечно',
 'кто',
 'куда',
 'ли',
 'лучше',
 'между',
 'меня',
 'мне',
 'много',
 'может',
 'можно',
 'мой',
 'моя',
 'мы',
 'на',
 'над',
 'надо',
 'наконец',
 'нас',
 'не',
 'него',
 'нее',
 'ней',
 'нельзя',
 'нет',
 'ни',
 'нибудь',
 'никогда',
 'ним',
 'них',
 'ничего',
 'но',
 'ну',
 'о',
 'об',
 'один',
 'он',
 'она',
 'они',
 'опять',
 'от',
 'перед',
 'по',
 'под',
 'после',
 'потом',
 'потому',
 'почти',
 'при',
 'про',
 'раз',
 'разве',
 'с',
 'сам',
 'свою',
 'себе',
 'себя',
 'сейчас',
 'со',
 'совсем',
 'так

In [21]:
news_embs=[]
title2index = {}
index2title = {}
for idx, title in enumerate(pd.read_csv("data/news_500.csv")['title'].values):
    tokens = word_tokenize(title)
    title2index[title] = idx
    index2title[idx] = title
    print(tokens)
    break
    
news_embs = th.tensor(news_embs)

['В.Путин', 'торопит', 'разработчиков', 'военной', 'реформы']


In [1]:
import pandas as pd

pd.read_parquet(r"C:\Users\Rog G16\Downloads\Telegram Desktop\smoothed_independent_class.parquet")

,latitude,longitude,canopy_height,beam,datetime,class_label,date_only,smoothed_height_median
0,61.501129,50.534298,19.574738,gt1l,2019-01-04 20:31:20.575826641,Forest,2019-01-04,21.249397
1,61.502914,50.534695,20.826653,gt1l,2019-01-04 20:31:20.547558971,Forest,2019-01-04,21.931168
2,61.505596,50.535301,19.818359,gt1l,2019-01-04 20:31:20.505220462,Forest,2019-01-04,21.249397
3,61.506489,50.535492,23.973160,gt1l,2019-01-04 20:31:20.491051752,Forest,2019-01-04,21.249397
4,61.507381,50.535690,21.931168,gt1l,2019-01-04 20:31:20.477009311,Forest,2019-01-04,21.243744
...,...,...,...,...,...,...,...,...
62,61.594936,50.555180,25.046219,gt1l,2019-01-04 20:31:19.095790442,Forest,2019-01-04,23.064590
63,61.595829,50.555378,19.623566,gt1l,2019-01-04 20:31:19.081765555,Forest,2019-01-04,21.956909
64,61.596722,50.555573,20.451019,gt1l,2019-01-04 20:31:19.067705140,Forest,2019-01-04,21.956909
65,61.597614,50.555775,17.317810,gt1l,2019-01-04 20:31:19.053574014,Forest,2019-01-04,21.956909


<p class="task" id="2"></p>

2\. Настройте модель Word2Vec из пакета `gensim`. Для валидации выведите на экран информацию о ближайших словах для нескольких случайно выбранных токенов из обучающей выборки.

- [ ] Проверено на семинаре

<p class="task" id="3"></p>

3. Опишите класс `W2VDataset`, который реализует в себе логику получения контекстного окна для обучения skip-gram модели. При создании словаря игнорируйте токены, которые встретились меньше 20 раз. Продемонстрируйте пример работы.

![image.png](https://github.com/OlgaChernytska/word2vec-pytorch/raw/main/docs/skipgram_overview.png)

- [ ] Проверено на семинаре

<p class="task" id="4"></p>

4\. Реализуйте и настройте skip-gram модель. Перед началом обучения выберите случайным образом несколько слов из датасета и для каждого из них выведите на экран 3 ближайших слова в смысле косинусной близости между эмбеддингами. В процессе настройки для валидации периодически выводите на экран информацию о ближайших словах для этих слов. Выведите на экран график значения функции потерь в зависимости от номера эпохи.  

![image.png](https://github.com/OlgaChernytska/word2vec-pytorch/raw/main/docs/skipgram_detailed.png)

- [ ] Проверено на семинаре

<p class="task" id="5"></p>

5\. Выберите одно слово из набора данных и найдите к нему топ-20 ближайших в смысле косинусной близости между эмбеддингами. Извлеките веса обученного слоя эмбеддингов из модели, обученной в предыдущем задании.

Используя PCA или t-SNE (из sklearn), сожмите вектора до размерности 2. Обратите внимание, что для обучения этих моделей нужно использовать весь набор векторов, а не только топ отобранных.

Визуализируйте отобранные слова. Прокомментируйте (текстом) полученный результат.

- [ ] Проверено на семинаре